# Generated by Django 5.1.4 on 2024-12-27 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0020_remove_order_deliverycontact"),
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryuser",
            name="address",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliveryuser",
            name="city",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.city",
            ),
        ),
        migrations.AddField(
            model_name="deliveryuser",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="deliveryuser",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="deliveryuser",
            name="place",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliveryuser",
            name="state",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.state",
            ),
        ),
        migrations.CreateModel(
            name="DeliveryPersonLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "delivery_person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="delivery.deliveryperson",
                    ),
                ),
            ],
        ),
    ]
