# Generated by Django 4.1.3 on 2024-12-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_contact_deliveryuser_feedback_delete_deliveryperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryuser',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
