# Generated by Django 4.2.9 on 2024-12-30 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryuser_address_deliveryuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypersonlocation',
            name='delivery_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliveryuser'),
        ),
        migrations.DeleteModel(
            name='DeliveryPerson',
        ),
    ]
