# Generated by Django 4.1.3 on 2024-12-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_deliveryuser_active_status_deliveryuser_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "vehicle_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("on-duty", "On Duty"),
                            ("off-duty", "Off Duty"),
                            ("delivering", "Delivering"),
                        ],
                        default="inactive",
                        max_length=10,
                    ),
                ),
                (
                    "current_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("available_for_delivery", models.BooleanField(default=True)),
                (
                    "bank_account_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("profile_picture_url", models.URLField(blank=True, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("vehicle_registration_date", models.DateField(blank=True, null=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
