# Generated by Django 4.2.9 on 2024-12-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_deliverypersonlocation_delivery_person_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
