# Generated by Django 4.1.3 on 2024-12-11 17:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryuser',
            name='active_status',
        ),
        migrations.RemoveField(
            model_name='deliveryuser',
            name='location',
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='deliveryContact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
