# Generated by Django 4.2.9 on 2024-12-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delete_contact_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryuser',
            name='phone',
            field=models.CharField(default=1234567890, max_length=50),
            preserve_default=False,
        ),
    ]
