# Generated by Django 4.1.3 on 2024-12-19 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_alter_customeruser_address'),
        ('delivery', '0005_remove_deliveryuser_active_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryuser',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.city'),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.place'),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.state'),
        ),
    ]
