# Generated by Django 5.1.4 on 2024-12-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_deliveryuser_city_deliveryuser_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryuser',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryuser',
            name='place',
            field=models.CharField(max_length=50),
        ),
    ]
