# Generated by Django 5.1.3 on 2024-12-23 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_deliveryuser_city_deliveryuser_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPersonLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('delivery_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliveryperson')),
            ],
        ),
    ]
