# Generated by Django 5.1.4 on 2024-12-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_deliverypersonlocation'),
        ('delivery', '0007_deliveryuser_latitude_deliveryuser_longitude_and_more'),
    ]

    operations = [
    ]
