# Generated by Django 4.1.3 on 2024-11-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminPrivilege",
            fields=[
                (
                    "AdminId",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("AdminPass", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("CartId", models.AutoField(primary_key=True, serialize=False)),
                ("CustEmail", models.CharField(max_length=50)),
                ("FoodId", models.CharField(max_length=50)),
                ("FoodQuant", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("CustomerId", models.AutoField(primary_key=True, serialize=False)),
                ("CustomerFName", models.CharField(max_length=30)),
                ("CustomerLName", models.CharField(max_length=30)),
                ("CustomerCont", models.CharField(max_length=10)),
                ("CustomerEmail", models.CharField(max_length=50)),
                ("CustomerPass", models.CharField(max_length=60)),
                ("Address", models.CharField(default="", max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                ("FoodId", models.AutoField(primary_key=True, serialize=False)),
                ("FoodName", models.CharField(max_length=30)),
                ("FoodCat", models.CharField(max_length=30)),
                ("FoodPrice", models.FloatField(max_length=15)),
                ("FoodImage", models.ImageField(default="", upload_to="media")),
            ],
        ),
        migrations.CreateModel(
            name="FoodOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("food_item", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("order_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
