# Generated by Django 5.1.3 on 2024-11-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_id_restaurant_restaurant_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_id',
            new_name='id',
        ),
    ]
