# Generated by Django 5.1.3 on 2024-11-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_restaurant_id_restaurant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='c_id',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='id',
            new_name='r_id',
        ),
    ]
