# Generated by Django 4.1.3 on 2024-12-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
