# Generated by Django 4.1.3 on 2024-12-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customeruser_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='hydrabad', max_length=255),
        ),
    ]
