# Generated by Django 4.1.3 on 2024-12-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='customer',
        ),
    ]
