# Generated by Django 4.1.3 on 2024-12-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_customeruser_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='address',
            field=models.CharField(default='hydrabad', max_length=50),
            preserve_default=False,
        ),
    ]
