# Generated by Django 4.1.3 on 2024-12-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_customeruser_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
