# Generated by Django 4.1.3 on 2024-12-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_alter_customeruser_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
