# Generated by Django 5.1.4 on 2024-12-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0018_alter_customeruser_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_contact",
        ),
        migrations.AddField(
            model_name="order",
            name="deliveryContact",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
