# Generated by Django 5.1.4 on 2024-12-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0019_remove_order_delivery_contact_order_deliverycontact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="deliveryContact",
        ),
    ]
