# Generated by Django 5.0.6 on 2024-11-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
