# Generated by Django 4.1.3 on 2024-12-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
