# Generated by Django 4.1.3 on 2024-11-25 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ordering',
        ),
    ]
