# Generated by Django 4.1.3 on 2024-12-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordering", "0002_delete_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
