# Generated by Django 4.1.3 on 2024-12-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_comment_comment_id'),
        ('ordering', '0004_feedback'),
    ]

    operations = [
    ]
