# Generated by Django 4.2.9 on 2024-12-31 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_merge_0002_comment_comment_id_0004_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
