# Generated by Django 5.1.3 on 2024-11-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(default='Unknown Address', max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('cuisine_type', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('website_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
