# Generated by Django 4.1.3 on 2024-12-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_alter_rating_restaurant"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
