# Generated by Django 4.1.3 on 2024-12-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_fooditems_restaurantname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='restaurantName',
            field=models.CharField(max_length=50),
        ),
    ]
