# Generated by Django 4.1.3 on 2024-12-08 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_fooditems_restaurantname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='restaurantName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='restaurant.restaurantuser'),
        ),
    ]
