# Generated by Django 4.1.3 on 2024-12-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_fooditems_restaurantname'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='category',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
