# Generated by Django 4.1.3 on 2024-12-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_restaurantuser_latitude_restaurantuser_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
