# Generated by Django 4.2.9 on 2024-12-31 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_alter_restaurantuser_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
